Add Dynatrace to landscape model
openapm/landscape-model pull request #175
Opened 2023-03-10 10:11 UTC by mreider

Added Dynatrace, OneAgent, ActiveGate, and Micrometer to the OpenAPM landscape.

2023-05-17 14:28 UTC, arile01 requested changes
Hey there, there are some unresolved references which need to be fixed as the data-model cannot be build otherwise. :) 
You can check if the model can be build with >$npm run-script build <

2023-05-17 14:28 UTC, arile01 commented on model/components/commercial/dynatrace.yml
> +      dataFrom:
influx, prometheus and jaeger need to actually reference another component id. So e.g. 'influxdata-influxdb' or 'influxdata-telegraf' instead. Which id's are available can be looked up in the respective component file yaml.

2023-05-17 14:28 UTC, arile01 commented on model/components/commercial/dynatrace.yml
> +        - prometheus
same here :)

2023-08-07 11:06 UTC, mreider commented
I think these satisfy your comments?

2024-02-29 16:59 UTC, merged